import { Router } from 'express'; import multer from 'multer'; import * as XLSX from 'xlsx'; import { db } from '../config/firebaseAdmin'; import { requireAuth, allowRoles } from '../middleware/auth'; import { audit } from '../middleware/audit'; import { asyncHandler } from '../utils/asyncHandler';
const router=Router(); const upload=multer({ storage:multer.memoryStorage(), limits:{ fileSize: 10*1024*1024 }});
router.use(requireAuth);
router.get('/', asyncHandler(async (req,res)=>{ let q:any=db.collection('leads'); if(!['CEO','Admin','Head Manager','Team Manager','Data Scraper'].includes(req.user!.role)) q=q.where('ownerId','==',req.user!.uid); const snap=await q.limit(500).get(); res.json(snap.docs.map((d:any)=>({id:d.id,...d.data()}))); }));
router.post('/', allowRoles('CEO','Admin','Head Manager','Team Manager','Sales Executive','Data Scraper'), audit('lead.create'), asyncHandler(async(req,res)=>{ const ref=await db.collection('leads').add({...req.body, createdBy:req.user!.uid, createdAt:new Date().toISOString(), updatedAt:new Date().toISOString()}); res.status(201).json({id:ref.id}); }));
router.patch('/:id', audit('lead.update'), asyncHandler(async(req,res)=>{ await db.collection('leads').doc(req.params.id).update({...req.body, updatedAt:new Date().toISOString()}); res.json({ok:true}); }));
router.delete('/:id', allowRoles('CEO','Admin','Head Manager','Team Manager'), audit('lead.delete'), asyncHandler(async(req,res)=>{ await db.collection('leads').doc(req.params.id).delete(); res.json({ok:true}); }));
router.post('/import', allowRoles('CEO','Admin','Head Manager','Team Manager','Data Scraper'), upload.single('file'), audit('lead.import'), asyncHandler(async(req,res)=>{ if(!req.file) return res.status(400).json({error:'file is required'}); const wb=XLSX.read(req.file.buffer); const rows:any[]=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]); const batch=db.batch(); const seen=new Set<string>(); let imported=0, duplicates=0; rows.forEach(row=>{ const key=(row.phone||row.Phone||row.email||row.Email||row.businessName||row['Business Name']||'').toString().toLowerCase(); if(seen.has(key)){ duplicates++; return; } seen.add(key); const ref=db.collection('leads').doc(); batch.set(ref,{ businessName:row.businessName||row['Business Name']||row.Name||'Untitled', phone:row.phone||row.Phone||'', email:row.email||row.Email||'', website:row.website||row.Website||'', address:row.address||row.Address||'', category:row.category||row.Category||'', rating:Number(row.rating||row.Rating||0), stage:'New Lead', source:'Import', tags:['imported'], createdAt:new Date().toISOString() }); imported++; }); await batch.commit(); res.json({ imported, duplicates }); }));
export default router;
